import type { HousingListing, NeighborhoodIntel, RoommateProfile } from './types';

const now = new Date().toISOString();

export const HOUSING_LISTINGS: HousingListing[] = [
  {
    id: 'hx-morningside-edu-sublet',
    sourceType: 'student_sublet',
    title: 'Verified Columbia sublet · private room near 116th',
    description: 'Private room in a 3BR apartment near Broadway/116th. Current tenant is a Columbia graduate student leaving for summer research. Furnished room, shared kitchen, video tour available, lease proof uploaded with private details redacted.',
    address: 'Broadway & W 116th St',
    lat: 40.8075,
    lng: -73.9630,
    borough: 'Manhattan',
    neighborhood: 'Morningside Heights',
    price: 1820,
    realMonthlyCost: 1895,
    deposit: 1820,
    brokerFee: 0,
    moveInDate: '2026-08-15',
    leaseEndDate: '2026-12-20',
    leaseTerm: 'sublet',
    roomType: 'private_room',
    bedrooms: 3,
    bathrooms: 1,
    furnished: true,
    noFee: true,
    amenities: ['furnished room', 'laundry nearby', 'video tour', '1 train access', 'student building'],
    commute: { toColumbia: 6, toNYU: 34, toFordham: 28, label: '6 min walk to Columbia' },
    posterName: 'Columbia Grad Student',
    isEduVerifiedPost: true,
    verificationStatus: 'proof_uploaded',
    riskScore: 18,
    riskLevel: 'low',
    riskReasons: ['Sublet permission should still be confirmed before payment.'],
    positiveSignals: ['.edu verified poster', 'proof uploaded', 'video tour available', 'no broker fee', 'specific address area'],
    matchScore: 94,
    matchReasons: ['Under $1,900 effective monthly cost', '6 min to Columbia', 'furnished private room', 'move-in matches August window', 'low risk score'],
    sourceUrl: undefined,
    images: [],
    status: 'active',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'hx-uws-building-no-fee',
    sourceType: 'building_website',
    title: 'Upper West Side no-fee studio · building availability',
    description: 'Studio availability from a managed building near 96th St. Good fit for students who prefer privacy and a safer-feeling late-night commute. Agent has not contacted leasing office yet; availability must be confirmed.',
    address: 'W 96th St & Broadway',
    lat: 40.7930,
    lng: -73.9725,
    borough: 'Manhattan',
    neighborhood: 'Upper West Side',
    price: 2860,
    realMonthlyCost: 2860,
    deposit: 2860,
    brokerFee: 0,
    moveInDate: '2026-08-01',
    leaseEndDate: '2027-07-31',
    leaseTerm: 'long_term',
    roomType: 'studio',
    bedrooms: 0,
    bathrooms: 1,
    furnished: false,
    noFee: true,
    amenities: ['elevator', 'laundry', 'managed building', 'near express train'],
    commute: { toColumbia: 15, toNYU: 29, toFordham: 34, label: '15 min to Columbia by subway/walk' },
    isEduVerifiedPost: false,
    verificationStatus: 'admin_verified',
    riskScore: 28,
    riskLevel: 'low',
    riskReasons: ['Availability and fees must be reconfirmed with leasing office.'],
    positiveSignals: ['managed building source', 'no fee claim', 'specific cross street', 'clear lease term'],
    matchScore: 82,
    matchReasons: ['Private studio', 'no broker fee', 'reasonable Columbia commute', 'managed building'],
    sourceUrl: 'https://example.com/uws-managed-building',
    images: [],
    status: 'active',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'hx-lic-roommate-share',
    sourceType: 'external_listing',
    title: 'LIC luxury 2BR roommate share · near E/M/7',
    description: 'Private bedroom in a Long Island City 2BR with doorman/gym. Better fit for NYU/Midtown internships than late-night Columbia life. Price is attractive for amenities but commute to Columbia is longer.',
    address: 'Court Square, LIC',
    lat: 40.7472,
    lng: -73.9436,
    borough: 'Queens',
    neighborhood: 'Long Island City',
    price: 2150,
    realMonthlyCost: 2290,
    deposit: 2150,
    brokerFee: 0,
    moveInDate: '2026-09-01',
    leaseEndDate: '2027-08-31',
    leaseTerm: 'lease_takeover',
    roomType: 'private_room',
    bedrooms: 2,
    bathrooms: 2,
    furnished: false,
    noFee: true,
    amenities: ['doorman', 'gym', 'in-unit laundry', 'newer building', 'subway hub'],
    commute: { toColumbia: 42, toNYU: 22, toFordham: 52, label: '42 min to Columbia, 22 min to NYU' },
    isEduVerifiedPost: false,
    verificationStatus: 'unverified',
    riskScore: 43,
    riskLevel: 'medium',
    riskReasons: ['External source not verified by AXIO7', 'longer Columbia commute', 'lease takeover details need written confirmation'],
    positiveSignals: ['specific neighborhood', 'amenities listed', 'no broker fee claim'],
    matchScore: 76,
    matchReasons: ['Strong amenities', 'reasonable price for LIC', 'good for NYU/Midtown', 'roommate share lowers cost'],
    sourceUrl: 'https://example.com/lic-roommate-share',
    images: [],
    status: 'active',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'hx-suspicious-midtown',
    sourceType: 'reviewed_link',
    title: 'Below-market Midtown room · needs verification',
    description: 'Private room in Midtown for $900. Poster asks for a deposit before video tour and gives only a vague address. AXIO7 keeps this visible only as a risk example until verified.',
    lat: 40.7549,
    lng: -73.9840,
    borough: 'Manhattan',
    neighborhood: 'Midtown',
    price: 900,
    realMonthlyCost: 900,
    moveInDate: '2026-08-01',
    leaseTerm: 'sublet',
    roomType: 'private_room',
    furnished: true,
    noFee: true,
    amenities: ['unclear'],
    commute: { toColumbia: 31, toNYU: 18, label: 'commute plausible but address missing' },
    isEduVerifiedPost: false,
    verificationStatus: 'unverified',
    riskScore: 86,
    riskLevel: 'high',
    riskReasons: ['Price far below nearby market', 'requests deposit before video tour', 'address is vague', 'poster is not .edu verified', 'sublet permission unclear'],
    positiveSignals: ['none yet — requires proof before contact'],
    matchScore: 41,
    matchReasons: ['Budget fit is strong but risk penalty is severe'],
    sourceUrl: 'https://example.com/review-needed',
    images: [],
    status: 'needs_review',
    createdAt: now,
    updatedAt: now,
  },
];

export const NYC_NEIGHBORHOODS: NeighborhoodIntel[] = [
  {
    slug: 'morningside-heights',
    name: 'Morningside Heights',
    borough: 'Manhattan',
    bestFor: ['Columbia students', 'late-night campus access', 'first NYC lease'],
    notIdealFor: ['large luxury inventory', 'cheap studios'],
    avgRentLevel: '$$$',
    commuteToColumbia: 5,
    commuteToNYU: 35,
    safetyFeeling: 'Campus-adjacent and familiar for Columbia students, with normal NYC block-by-block variation.',
    studentFriendliness: 'Very high',
    pros: ['walkable to Columbia', 'student density', 'easy 1 train access', 'many sublets'],
    cons: ['limited inventory', 'higher rent near campus', 'rooms move quickly'],
    agentSummary: 'Best default area for Columbia newcomers who value certainty, fast commute, and campus life over maximum apartment space.',
  },
  {
    slug: 'upper-west-side',
    name: 'Upper West Side',
    borough: 'Manhattan',
    bestFor: ['safer-feeling residential blocks', 'Columbia/NYU balance', 'managed buildings'],
    notIdealFor: ['lowest budget renters', 'party-heavy lifestyle'],
    avgRentLevel: '$$$$',
    commuteToColumbia: 15,
    commuteToNYU: 30,
    safetyFeeling: 'Generally calmer and residential, especially near major avenues and subway access.',
    studentFriendliness: 'High but expensive',
    pros: ['good subway access', 'parks', 'residential feel', 'managed inventory'],
    cons: ['expensive studios', 'competitive no-fee units', 'older building quirks'],
    agentSummary: 'A strong Columbia option for renters with budget flexibility who want a quieter neighborhood and more managed-building inventory.',
  },
  {
    slug: 'long-island-city',
    name: 'Long Island City',
    borough: 'Queens',
    bestFor: ['NYU/Midtown commuters', 'newer buildings', 'amenities'],
    notIdealFor: ['late-night Columbia commute', 'ultra-low budget'],
    avgRentLevel: '$$$',
    commuteToColumbia: 42,
    commuteToNYU: 22,
    safetyFeeling: 'Modern high-rise pockets feel polished, but commute and station access matter a lot.',
    studentFriendliness: 'Medium',
    pros: ['newer buildings', 'subway hub', 'amenity inventory', 'views'],
    cons: ['longer Columbia commute', 'high amenity rents', 'less campus community'],
    agentSummary: 'Great for newer-building seekers and Midtown/NYU access; not the default Columbia choice unless amenities matter more than commute.',
  },
  {
    slug: 'jersey-city',
    name: 'Jersey City',
    borough: 'New Jersey nearby',
    bestFor: ['budget tradeoffs', 'PATH commuters', 'larger apartments'],
    notIdealFor: ['Columbia daily commute', 'students needing NYC-only simplicity'],
    avgRentLevel: '$$',
    commuteToColumbia: 58,
    commuteToNYU: 32,
    safetyFeeling: 'Varies strongly by station and building; PATH access is the key constraint.',
    studentFriendliness: 'Medium-low for Columbia, medium for downtown internships',
    pros: ['more space', 'some cheaper units', 'PATH to downtown', 'newer towers'],
    cons: ['long Columbia commute', 'PATH dependency', 'cross-state logistics'],
    agentSummary: 'Usually not ideal for Columbia newcomers unless budget and space beat commute simplicity. Better for downtown work or NYU-adjacent routines.',
  },
  {
    slug: 'williamsburg',
    name: 'Williamsburg',
    borough: 'Brooklyn',
    bestFor: ['social lifestyle', 'restaurants/nightlife', 'Brooklyn community'],
    notIdealFor: ['Columbia convenience', 'quiet low-budget housing'],
    avgRentLevel: '$$$$',
    commuteToColumbia: 50,
    commuteToNYU: 24,
    safetyFeeling: 'Popular and active, but expensive and not commute-optimized for uptown campuses.',
    studentFriendliness: 'Medium for NYU, low for Columbia',
    pros: ['lifestyle', 'food/nightlife', 'creative community', 'L train access'],
    cons: ['expensive', 'long Columbia commute', 'competitive rooms'],
    agentSummary: 'A lifestyle-first choice. Strong for NYU or downtown work, weaker for Columbia unless social scene matters more than commute.',
  },
];

export const ROOMMATE_PROFILES: RoommateProfile[] = [
  {
    id: 'rm-ivy-columbia-quiet',
    userId: 'seed-roommate-1',
    name: 'Ivy',
    school: 'Columbia',
    budget: 1850,
    moveInDate: '2026-08-20',
    preferredNeighborhoods: ['Morningside Heights', 'Upper West Side'],
    sleepSchedule: 'early-ish',
    cleanliness: 'very clean',
    noiseTolerance: 'quiet',
    socialLevel: 'friendly but independent',
    cookingFrequency: 'often',
    intro: 'Incoming Columbia MA student looking for a calm apartment within 30 minutes of campus.',
    verified: true,
  },
  {
    id: 'rm-ryan-nyu-social',
    userId: 'seed-roommate-2',
    name: 'Ryan',
    school: 'NYU',
    budget: 2100,
    moveInDate: '2026-09-01',
    preferredNeighborhoods: ['East Village', 'Williamsburg', 'Long Island City'],
    sleepSchedule: 'late',
    cleanliness: 'clean common areas',
    noiseTolerance: 'moderate',
    socialLevel: 'social',
    cookingFrequency: 'rarely',
    intro: 'NYU newcomer prioritizing transit, restaurants, and a roommate who is okay with occasional guests.',
    verified: true,
  },
  {
    id: 'rm-mina-parsons',
    userId: 'seed-roommate-3',
    name: 'Mina',
    school: 'Parsons',
    budget: 1700,
    moveInDate: '2026-08-10',
    preferredNeighborhoods: ['Bushwick', 'Downtown Brooklyn', 'Astoria'],
    sleepSchedule: 'flexible',
    cleanliness: 'balanced',
    noiseTolerance: 'moderate',
    socialLevel: 'quiet creative',
    cookingFrequency: 'sometimes',
    intro: 'Design student looking for a practical room and a respectful roommate setup.',
    verified: false,
  },
];
